### ISSUE TITLE
We need to compile the @atlaskit components from node_modules

### ISSUE THREAD

**Issue by ajaymathur** [jim-king-2000/nextbugrepro#1]
The Atlaskit components are only released as ESM and no more CJS thus we would need to compile them too.

Solution: 

Extends the webpack config to transpile the packages starting with `@atlaskit`.

**Comment by jim-king-2000** [comment]
I'm using a lot of @atlaskit components such as "@atlaskit/checkbox", "@atlaskit/datetime-picker" and "@atlaskit/form", etc. None of them need to be compiled. Why "@atlaskit/tooptip" need to be compiled?

**Comment by jim-king-2000** [comment]
I compiled "node_modules/@atlaskit". Still no tooltip.

**Comment by jim-king-2000** [comment]
Forget it. I have switched to Grommet V2.
